repositories:
  # moveit2:
  #   type: git
  #   url: https://github.com/ros-planning/moveit2
  #   version: main
  control_msgs:
    type: git
    url: https://github.com/ros-controls/control_msgs.git
    version: foxy-devel
  geometric_shapes:
    type: git
    url: https://github.com/ros-planning/geometric_shapes.git
    version: ros2
  moveit_msgs:
    type: git
    url: https://github.com/ros-planning/moveit_msgs.git
    version: ros2
  moveit_resources:
    type: git
    url: https://github.com/ros-planning/moveit_resources.git
    version: ros2
  realtime_tools:
    type: git
    url: https://github.com/ros-controls/realtime_tools.git
    version: foxy-devel
  ros2_control:
    type: git
    url: https://github.com/ros-controls/ros2_control.git
    version: master
  ros2_controllers:
    type: git
    url: https://github.com/ros-controls/ros2_controllers.git
    version: master
  srdfdom:
    type: git
    url: https://github.com/ros-planning/srdfdom.git
    version: ros2
  warehouse_ros:
    type: git
    url: https://github.com/ros-planning/warehouse_ros.git
    version: ros2
