# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

# notifications:
#   email:
#     recipients:
#       - zelenak@picknik.ai

env:
  global: # default values that are common to all configurations (can be overriden below)
    - ROS_DISTRO=foxy      # ROS distro to test for
    - ROS_REPO=ros         # ROS binary repository [ros | ros-shadow-fixed]
    - TEST_BLACKLIST=      # list packages, for which to skip the unittests
    - UPSTREAM_WORKSPACE=.repos.yaml # pull in packages from a local
    - WARNINGS_OK=false    # Don't accept warnings [true | false]
    # .repos file FIXME -Werror disabled because of compiler warnings
    # in geometric_shapes ("redundant redeclaration of ‘void
    # qh_[...]’")
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-function"

jobs:
  fast_finish: true
  include:
    - name: "[Foxy] - clang-format, ament_lint"
      env: TEST="clang-format ament_lint"
    # - name: "[Foxy] - code-coverage"
    #   env: TEST=code-coverage
    - name: "[Foxy] - gcc (build,test)"
      env: ROS_DISTRO=foxy
    - name: "[Foxy] - clang (build,test,clang-tidy-fix)"
      compiler: clang
      env: TEST=clang-tidy-fix
           CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-overloaded-virtual"

before_script:
  # Clone the moveit_ci repository into Travis' workspace
  - git clone --depth 1 -q https://github.com/ros-planning/moveit_ci.git -b ros2 .moveit_ci

script:
  # Run the test script
  - .moveit_ci/travis.sh
