
control_manager:
  ros__parameters:
    controllers:
      - joint_trajectory_controller_position

    joint_trajectory_controller_position:
      type: joint_trajectory_controller/JointTrajectoryController

forward_command_controller_position:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    interface_name: position
